export const MAKE_NEW_EMPTY_FORMULA = "MAKE_NEW_EMPTY_FORMULA";
export const ADD_LOG = "ADD_LOG";
export const CLEAR_LOG = "CLEAR_LOG";
export const LOADING = "LOADING";
export const CHANGE_PRICE_TYPE = "CHANGE_PRICE_TYPE"
export const CHANGE_CALC_FROM_SALE_PRICE = "CHANGE_CALC_FROM_SALE_PRICE"
export const CHANGE_FORMULA = "CHANGE_FORMULA"
export const LOAD_FORMULAS = "LOAD_FORMULAS"

export const CHANGE_CHECK_RRC = "CHANGE_CHECK_RRC"
export const CHANGE_PARAMETERS = "CHANGE_PARAMETERS"

export const LOAD_SUPPLIERS = "LOAD_SUPPLIERS"
export const CHANGE_RRC_SUPPLIERS = "CHANGE_RRC_SUPPLIERS"

export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS"
export const CHANGE_CITY = "CHANGE_CITY"

export const LOAD_FORMULA_FULL_DATA = "LOAD_FORMULA_FULL_DATA"
export const RESET_FORMULA = "RESET_FORMULA"

