<?php

return [
    "shop" => "Магазин",
    "number_source" => "№ заказа Источник",
    "supplier_number" => "Поставщик № заказа",
    "status" => "Статус заказа",
    "date_create" => "Дата и время заказа",
    "date_delivery" => "Дата отгрузки заказа",
    "basket" => "Состав заказа",
    "quantity" => "Кол-во",
    "site_price" => "Цена на сайте",
    "sale" => "Цена продаж",
    "purchase" => "Цена закупки",
    "commission" => "Комиссия",
    "commission_supplier" => "Комиссия поставщика",
    "client" => "Клиент",
    "manager" => "Менеджер",
    "city" => "Город",
    "pay_type" => "Способ оплаты",
    "instal" => "Установка",
    "fines" => "Штрафы",
    "agreed_client" => "Согласовано клиент",
    "agreed_supplier" => "Согласовано поставщик",
    "test" => "Тест",
];